<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZbvHtM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZbvHtM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMZbvHtM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMZbvHtM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMZbvHtM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MZbvHtM',
    'container.build_id' => '9351abf3',
    'container.build_time' => 1611324218,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZbvHtM');
