<?php 

$torneos="
1-9-LIGA TERCERA DIVISION NACIONAL,
1-10-LIGA SEGUNDA DIVISION FEMENINA,
1-11-LIGA DIVISION DE HONOR JUVENIL,
1-12-LIGA PREFERENTE INTERINSULAR,
1-13-LIGA PRIMERA REGIONAL DE GRAN CANARIA,
1-14-LIGA SEGUNDA REGIONAL DE GRAN CANARIA,
1-15-LIGA PREFERENTE JUVENIL DE GRAN CANARIA,
1-16-LIGA PRIMERA JUVENIL DE GRAN CANARIA,
1-17-LIGA SEGUNDA JUVENIL DE GRAN CANARIA,
1-18-LIGA CADETE PREFERENTE DE GRAN CANARIA,
1-19-LIGA PRIMERA CADETE DE GRAN CANARIA,
1-20-LIGA INFANTIL PREFERENTE DE GRAN CANARIA,
1-21-LIGA PRIMERA INFANTIL DE GRAN CANARIA,
1-22-LIGA PREFERENTE ALEVIN F-8 GRAN CANARIA,
1-23-LIGA PRIMERA ALEVIN F-8 GRAN CANARIA,
1-24-LIGA PREFERENTE BENJAMIN F-8 GRAN CANARIA,
1-25-LIGA PRIMERA BENJAMIN F-8 GRAN CANARIA,
1-26-LIGA DE VETERANOS GRAN CANARIA,
1-27-LIGA PREFERENTE INFANTIL LANZAROTE,
1-28-LIGA PRIMERA REGIONAL LANZAROTE,
1-29-LIGA PRIMERA INFANTIL DE LANZAROTE,
1-30-COPA PRIMERA REGIONAL DE LANZAROTE,
1-31-LIGA JUVENIL PREFERENTE DE LANZAROTE,
1-32-LIGA PREFERENTE ALEVIN F-8 DE LANZAROTE,
1-33-LIGA PRIMERA ALEVIN F-8 DE LANZAROTE,
1-34-LIGA PREFERENTE BENJAMIN F-8 DE LANZAROTE,
1-35-LIGA PRIMERA BENJAMIN F-8 DE LANZAROTE,
1-36-LIGA PRIMERA CADETE DE LANZAROTE,
1-37-COPA FEMENINA FUERTEVENTURA,
1-38-LIGA CADETE FUERTEVENTURA,
1-39-LIGA BENJAMIN F-8 FUERTEVENTURA,
1-40-LIGA FEMENINA LANZAROTE-FUERTEVENTURA,
1-41-LIGA JUVENIL PREFERENTE FUERTEVENTURA,
1-42-LIGA INFANTIL FUERTEVENTURA,
1-43-LIGA ALEVIN F-8 FUERTEVENTURA,
1-44-COPA PRIMERA REGIONAL FUERTEVENTURA,
1-45-LIGA SEGUNDA DIVISION B NACIONAL FUTBOL SALA,
1-46-LIGA PREFERENTE FUTBOL SALA FEMENINO GRAN CANARIA,
1-47-LIGA JUVENIL FÚTBOL SALA,
1-48-LIGA PRIMERA CADETE FUTBOL SALA GRAN CANARIA,
1-49-LIGA SEGUNDA CADETE FUTBOL SALA GRAN CANARIA,
1-50-LIGA JUVENIL DIVISION DE HONOR FUTBOL SALA,
1-51-LIGA PRIMERA INFANTIL FUTBOL SALA GRAN CANARIA,
1-52-LIGA PRIMERA ALEVIN FUTBOL SALA GRAN CANARIA,
1-53-LIGA PRIMERA BENJAMIN FUTBOL SALA GRAN CANARIA,
1-54-LIGA PRIMERA REGIONAL FUERTEVENTURA,
1-55-COPA FIFLP VETERANOS,
1-56-COPA FEMENINA LANZAROTE,
1-57-LIGA PREBENJAMIN DE GRAN CANARIA,
1-58-FINAL COPA PRIMERA REGIONAL CABILDO DE LANZAROTE,
1-59-FINAL COPA FEMENINA CABILDO DE LANZAROTE,
1-60-CUARTOS DE FINAL COPA FIFLP VETERANOS,
1-61-COPA JUVENIL FUTBOL SALA,
1-62-LIGA FEMENINA TERRITORIAL,
1-63-SUPERCOPA VETERANOS,
1-64-LIGA JUVENIL SALA LANZAROTE,
1-65-TERCERA DIVISION NACIONAL FUTBOL SALA,
1-66-FINAL COPA REGIONAL FUERTEVENTURA";

$torneosTenerife="
-COPA HELIODORO RODRIGUEZ LOPEZ LA PALMA
-COPA R.F.E.F.
-TERCERA DIVISIÓN
-LIGA NACIONAL DE HONOR JUVENIL
-COPA HELIODORO RODRIGUEZ LOPEZ 1ª FASE
-COPA HELIODORO RODRIGUEZ LOPEZ 2ª FASE
-COPA HELIODORO RODRIGUEZ LOPEZ 3ª FASE
-COPA HELIODORO RODRIGUEZ LOPEZ LA GOMERA
-COPA HELIODORO RODRIGUEZ LOPEZ LA PALMA
-INTERINSULAR PREFERENTE
-PRIMERA INTERINSULAR
-SEGUNDA INTERINSULAR
-COPA JOSE GLEZ. RGUEZ. LA PALMA
-COPA JOSE GLEZ. RGUEZ. LA PALMA (FINAL)
-SEGUNDA DIVISION NACIONAL FEMENINA
-FEMINAS PREFERENTE
-FEMINAS PRIMERA
-COPA FCO. JAVIER FELIP FEM. PRIMERA
-COPA FCO. JAVIER FELIP FEM. PRIMERA   2ª FASE
-COPA INFANTE PERAZA FEM. PREFERENTE 2ª FASE
-COPA INFANTE PERAZA FEM. PREFERENTE
-LIGA FERNANDO COVA - JUV. PREF.-
-LIGA JOSE A. FUMERO - 1ª JUV-
-LIGA SEGUNDA JUVENIL
-LIGA JOSE D. GOMEZ - CAD. PREF-
-LIGA CADETES DE PRIMERA
-CADETES LA GOMERA
-INFANTILES 1-FASE
-INFANTILES PREFERENTE
-INFANTILES PRIMERA
-INFANTILES SEGUNDA
-INFANTILES LA GOMERA
-ALEVINES 1 ª FASE
-ALEVINES PREFERENTE
-ALEVINES PRIMERA
-ALEVINES SEGUNDA
-ALEVINES LA GOMERA
-BENJAMINES 1ª FASE
-BENJAMINES PREFERENTE
-BENJAMINES PRIMERA
-BENJAMINES SEGUNDA
-BENJAMINES LA GOMERA
-PREBENJAMINES 1ª FASE
-PREBENJAMINES PREFERENTE
-PREBENJAMINES PRIMERA
-PREBENJAMINES SEGUNDA
-PREBENJAMINES LA GOMERA
-DEBUTANTE
-SEGUNDA DIVISIÓN NACIONAL B SALA
-TERCERA DIVISIÓN NACIONAL SALA
-PRIMERA TERRITORIAL FÚTBOL SALA
-PRIMERA TERRITORIAL FÚTBOL SALA FEMENINO
-DIVISION HONOR JUVENIL F.S.
-JUVENILES PREFERENTE FÚTBOL SALA
-CADETES FÚTBOL SALA
-FASE CAMPEONES CADETES FÚTBOL SALA
-COPA FEDERACIÓN CADETES SALA
-INFANTILES PREFERENTE FÚTBOL SALA
-INFANTILES PRIMERA FÚTBOL SALA
-INFANTILES SEGUNDA FÚTBOL SALA
-ALEVINES PREFERENTE FÚTBOL SALA
-ALEVINES PRIMERA FÚTBOL SALA
-ALEVINES SEGUNDA FÚTBOL SALA
-BENJAMINES PREFERENTE FÚTBOL SALA
-BENJAMINES PRIMERA FÚTBOL SALA
-BENJAMINES SEGUNDA FÚTBOL SALA
-PREBENJAMINES FÚTBOL SALA";
?>