<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fvgqQaT' shared service.

return $this->privates['.service_locator.fvgqQaT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'equiposRepository' => ['privates', 'App\\Repository\\EquiposRepository', 'getEquiposRepositoryService.php', true],
    'partidoRepository' => ['privates', 'App\\Repository\\PartidoRepository', 'getPartidoRepositoryService.php', true],
], [
    'equiposRepository' => 'App\\Repository\\EquiposRepository',
    'partidoRepository' => 'App\\Repository\\PartidoRepository',
]);
