<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.uSo_hBO' shared service.

return $this->privates['.service_locator.uSo_hBO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'equiposRepository' => ['privates', 'App\\Repository\\EquiposRepository', 'getEquiposRepositoryService.php', true],
    'noticia' => ['privates', '.errored..service_locator.uSo_hBO.App\\Entity\\Noticias', NULL, 'Cannot autowire service ".service_locator.uSo_hBO": it references class "App\\Entity\\Noticias" but no such service exists.'],
    'partidoRepository' => ['privates', 'App\\Repository\\PartidoRepository', 'getPartidoRepositoryService.php', true],
], [
    'equiposRepository' => 'App\\Repository\\EquiposRepository',
    'noticia' => 'App\\Entity\\Noticias',
    'partidoRepository' => 'App\\Repository\\PartidoRepository',
]);
