<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nZ424gn' shared service.

return $this->privates['.service_locator.nZ424gn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'noticiasRepository' => ['privates', 'App\\Repository\\NoticiasRepository', 'getNoticiasRepositoryService.php', true],
], [
    'noticiasRepository' => 'App\\Repository\\NoticiasRepository',
]);
